# -*- coding: utf-8 -*-
"""acessandoUOL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_UAeqxNb5nXmieZI-R0ICbuwGMb9VFki
"""

#pip install beautifulsoup4

#pip install requests

from logging import exception
import requests as r
from bs4 import BeautifulSoup

try:
  resultado = r.get("https://www.uol.com.br/")
except Exception as erro:
  print("ERRO",erro)
else:
  resposta = resultado.text
  soup = BeautifulSoup(resposta, 'html.parser')

  print(soup.p['class'])